### ISSUE TITLE
increase docstring coverage

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#129]
After #124 
- [ ] increase the number of docstrings, now evaluated with `interrogate`
- [ ] ratchet up `fail-under = 40` to a higher number in `pyproject.toml`

* Don't include type information because that is given in the type hints which are (or will be in the function signature)

**Comment by jpreszler** [comment]
I've begun work on this to learn the package better. I should have it done within the next week - getting the example usages will take a little time.

**Comment by drbenvincent** [comment]
Fantastic. Expecting the birth of our first child any moment now, so excuse any delays in reviewing the PR.

**Comment by jpreszler** [comment]
There's the PR. In retrospect, I probably should have done it in chunks because it's fairly large.

Between the new addition to your family (I hope everything will go, or has gone, smoothly) and the size of this, I'm not expecting a quick review. Hopefully the fact that you wrote the code this documents means the review isn't as bad as if I was adding 1K lines of code :) 

Please don't hesitate to flag changes you would like or inconsistencies you see.

**Comment by drbenvincent** [comment]
Closed by #232
