### ISSUE TITLE
ITS on click rate impressions divergence problem

### ISSUE THREAD

**Issue by priamai** [pymc-labs/CausalPy#231]
Hi there,
I am quite new so trying to learn by doing a simple ITS example on real click impression data.
On this notebook: (https://colab.research.google.com/drive/18LotGIkUY80EsAdmkqG53RhnuDlR7J7I?usp=sharing)

I am getting this error:

```
Sampling 4 chains for 1_000 tune and 1_000 draw iterations (4_000 + 4_000 draws total) took 408 seconds.
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
There were 439 divergences after tuning. Increase `target_accept` or reparameterize.
Chain 0 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
Chain 1 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
Chain 2 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
Chain 3 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
Sampling: [beta, sigma, y_hat]
Sampling: [y_hat]
Sampling: [y_hat]
/opt/conda/lib/python3.10/site-packages/arviz/stats/stats.py:1121: RuntimeWarning: invalid value encountered in divide
  r_squared = var_y_est / (var_y_est + var_e)
Sampling: [y_hat]
Sampling: [y_hat]
```
Are there any simple guidelines to tune the max_treedepth or target_accept?
I don't know even how to pass those parameters.

**Comment by drbenvincent** [comment]
Hi @priamai.

## Problem 1
The `treatment_time` is right at the start of the timeseries. So there are no pre-treatment observations.

## Problem 2
Plotting the dataset, we have predictor variables which vary quite a lot in terms of their scale. For example `impressions` are up around 10,000, but `position` is in the 10's and `ctr` are in the 1's. So it is quite likely that the corresponding slope parameters for each of the continuous variables will vary quite a lot. That is basically not playing well with the current priors in the `cp.pymc_models.LinearRegression` model.

So in an ideal world you'd either standardise the continuous predictors OR provide custom priors for each of the continuous predictors. A current limitation with CausalPy is that users can't do this.

We want to extent CausalPy to be able to do this. It wouldn't be that hard, but it would also reinvent the wheel as `bambi` already has this functionality. So a planned improvement is to use `bambi` models (rather than the current `cp.pymc_models.LinearRegression` model). There's an issue for this (#22) it's just a matter of finding the time to get to this.

So practically, the most promising approach for this dataset in the short term is to standardise the continuous predictors. 

Happy to hear whether you have success or not.

**Comment by drbenvincent** [comment]
PS. You can pass those parameters like this:

```python
cp.pymc_models.LinearRegression(sample_kwargs={"random_seed": seed, "target_accept": 0.97})
```

Though the problems mentioned above need to be resolved before resorting to tweaking sampling parameters.

**Comment by priamai** [comment]
Wow thanks for the insights:
Problem 1) I can easily fix that
Problem 2) okay I can a) standardize the inputs b) use Bambi I am reading it now.

**Comment by drbenvincent** [comment]
> Wow thanks for the insights:
> 
> Problem 1) I can easily fix that
> 
> Problem 2) okay I can a) standardize the inputs b) use Bambi I am reading it now.

Just to make sure I was clear... Bambi isn't yet integrated into CausalPy. But standardising should hopefully result in better results.

**Comment by priamai** [comment]
Yeah it's all new to me, it says Bambi is based on PyMC but also this project is based on PyMC.

**Comment by drbenvincent** [comment]
Just going through issues, so will close this. Feel free to re-open if there's anything remaining.
