### ISSUE TITLE
System error when importing CausalPy

### ISSUE THREAD

**Issue by kloskas** [pymc-labs/CausalPy#251]
After installing the package using the shell, when I try to import the package in a .ipynb but I get the message "SystemError: initialization of _internal failed without raising an exception"

Can you help pointing out the root cause and how to fix it? Thanks!

**Comment by drbenvincent** [comment]
Hi @kloskas. Thanks for this. I've not experienced that error, so I don't have any immediate solution that comes to mind. Because the description is quite brief, can you say a bit more? What version are you downloading? Presumably you pip installed it? To check if it's a CausalPy issue, does this error only happen when importing CausalPy but not other packages? Are you on Windows, Mac, or Linux? Is this being tried in a fresh environment?

**Comment by kloskas** [comment]
Apologies, sure I can provide more detail:
1.- pip installed in prompt, the current version (didn't specify it says CausalPy-0.1.1)
2.- OS windows 10 enterprise v. 22H2 x64
3.- error only happens with CausalPy (other packages installed)
4.- local environment, not fresh
5.- tried to reinstall again

Just wanted to understand if it was something unexpected (seems it is), before cleaning everything and having to reinstall conda + packages (my last option, if there's nothing else)

**Comment by kloskas** [comment]
I had to reinstall the environment. Now it works fine.
