### ISSUE TITLE
Paper reference for the causalpy bayesian synthetic control

### ISSUE THREAD

**Issue by xinliy123** [pymc-labs/CausalPy#265]
Hi, thanks for the package! I would like to know which paper method do you use for implement the Bayesian synthetic control method? Any references to the underlying paper or method would be helpful, thanks!

**Comment by drbenvincent** [comment]
Thanks for the feedback @xinliy123. Sorry for the delayed reply. I didn't implement this from a paper because it's pretty simple. It's basically just linear regression but with a constraint that the weights sum to 1, and that was achieved with a Dirichlet prior. See the `WeightedSumFitter` class for the actual code.
