### ISSUE TITLE
check what is run with `make doctest` and `make test`

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#278]
* Running `make doctest` locally took over 5 mins and there were 84 passing tests. 
* Running `make test` locally took just over 2 mins with 62 passing tests.

Something about `make doctest` doesn't sound right. I don't think we have anywhere close to 84 docstrings that need doctest. Maybe it's additionally running the regular tests on top of the doctests? Either way, it would be great to get to the bottom of this to save time and local and remote compute time.

Tagging @jpreszler just in case you're interested in taking a look into this.

**Comment by jpreszler** [comment]
Here's a PR for an improvement. https://github.com/pymc-labs/CausalPy/pull/280

The tests were getting run twice, but doctests still take a while. This is mainly because some of the tests require doing enough MCMC sampling for numeric stability in the examples. There's likely ways to save time here also, but it's not a simple as just reducing the pytest test collection.

**Comment by drbenvincent** [comment]
Closed by #280
