### ISSUE TITLE
Make docstring examples more stable

### ISSUE THREAD

**Issue by jpreszler** [pymc-labs/CausalPy#284]
Several of the docstring examples have numeric output that changes too much leading to doctest failures.

We should change the data and models in those examples (particularly PrePostFit and RegressionDiscontinuity) to have more stability even if the examples become unrealistic or 'silly' - they will illustrate basic usage and ensure documentation is up to date with code, leaving the main docs for real examples and detailed instruction.

The main goal is that doctests should always pass unless there's been a clear change in how a function works.

**Comment by jpreszler** [comment]
I'll try to get this done over the next week.

**Comment by drbenvincent** [comment]
I was too hasty in merging #285.

Looking into it in more detail, it looks like we are getting non reproducible results. This seems to be because we are only ingesting the sample kwargs into `pm.sample`. So the `random_seed` kwarg is not being passed into `pm.sample_prior_predictive` or `pm.sample_posterior_predictive`.

We can't simply unpack the provided kwargs into these function calls because they don't accept all the same kwargs as `pm.sample`. 

I'll submit a PR for this.
