### ISSUE TITLE
readme issue causalimpact

### ISSUE THREAD

**Issue by dirknbr** [pymc-labs/CausalPy#80]
I think your description (table) is wrong, CausalImpact is a synthetic control method.

**Comment by drbenvincent** [comment]
Hi @dirknbr. Thanks for the issue! So I think you are right - the [original paper](https://storage.googleapis.com/pub-tools-public-publication-data/pdf/41854.pdf) is full of the term "synthetic control" and seems pretty clear about this. I'm very happy to update this in the docs and readme, but I think it's worth getting people's opinion about whether it _is even worth drawing a distinction between synthetic control and interrupted time series?_

Both are just "models to come up with a counterfactual from time series data". So in a way they are the same thing. I had only made a distinction between the two because synthetic control and interrupted time series are two distinct terms used. My interpretation was that **synthetic control** was a special case where the predictor variables are basically untreated units, but of the same nature as the treated unit. An example would be geographical areas where the outcome might be sales in area T, and the predictors are sales in areas A, B, C.... Whereas with **interrupted time series**, the predictor variables are not of the same type. For example, if the outcome variable was "number of deaths in country T" then predictors would not have to be number of deaths in another country, but could be things such as temperature or prevalence of a disease over time.

Im interested in what people think. I'm happy to fix the description as @dirknbr points point. But does it make sense to keep (and clarify) the distinction between synthetic control and interrupted time series, or shall we just delete the concept of interrupted time series?

Tagging @cluhmann and @juanitorduz for opinions, but would love to hear from others.

**Comment by juanitorduz** [comment]
I am probably not 100% on top of the literature and terminology, but in my understanding, I agree with Ben. Moreover, I often use the term synthetic control in the context described above and when we further impose the condition on the weights (positive and add up to one). Again, please take this just as an opinion :)

**Comment by drbenvincent** [comment]
These papers suggest that at least the epidemiology literature treat SC and ITS as different things:
* Can synthetic controls improve causal inference in interrupted time series evaluations of public health interventions? https://pubmed.ncbi.nlm.nih.gov/33005920/
* Combining synthetic controls and interrupted time series analysis to improve causal inference in program evaluation https://pubmed.ncbi.nlm.nih.gov/29356225/

Will need to dig into this, so this is already looking like a pretty good Issue 🙂

**Comment by drbenvincent** [comment]
So the immediate concern has been addressed 👍🏻 I'll leave this issue open for a few days in case we get any more input. Otherwise I'll create a separate issue to generate a Glossary in the docs. I think that would be very useful.
