### ISSUE TITLE
After installing CausalPy via pip, /data folder isn't deployed as part of the package

### ISSUE THREAD

**Issue by pmarkoo** [pymc-labs/CausalPy#81]
This issue effectively disables the user to run code from https://causalpy.readthedocs.io/en/latest/ out of the box.

![Screenshot from 2022-11-22 19-23-59](https://user-images.githubusercontent.com/16898896/203392211-5c943e32-b549-4add-a29c-acaca6fc93bd.png)

**Comment by pmarkoo** [comment]
On top of that, used lib path is wrong, should be rather:
`
rd_data_path = "/".join(causalpy.__file__.split("/")[:-1]) + '/data/drinking.csv'
`

**Comment by drbenvincent** [comment]
Thanks for this, this is very helpful! I'll get on this as soon as I can. 

In the mean time if you were burning to run this _now_ then you can grab the data folder from GitHub https://github.com/pymc-labs/CausalPy/tree/main/causalpy/data

**Comment by drbenvincent** [comment]
Hi @pmarkoo. This should now be resolved. I've minted a new release, so you should be able to pip install CausalPy and run the example. I've tested this, so it should be good to go, but I'd definitely like to hear if it's still problematic for you.

There's a small known issue of plots not appearing when running from an ipython session rather than a notebook. But that is on the list to deal with, #86

**Comment by pmarkoo** [comment]
Thank you so much @drbenvincent for addressing this so quickly! Thanks for all the amazing work on the amazing package!

**Comment by drbenvincent** [comment]
Thanks @pmarkoo. Happy to get any more feedback or bug reports. Although focussing on my upcoming PyData talk, so might not be as responsive for about a week.

Just in case you tried to `pip install causalpy` recently and got errors, this is now fixed. There was a frustrating issue which broke the build. But as far as I can tell, things are working properly with 0.0.4
